; PlatformIO Project Configuration File
; Coche Radiocontrol ESP32 - Emisor y Receptor

[env:mando]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_emisor.cpp> +<*> -<main_receptor.cpp>
lib_deps = 
    ESP32Servo

[env:coche]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_receptor.cpp> +<*> -<main_emisor.cpp>
lib_deps = 
    ESP32Servo
